### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by axeberg** [chas-academy/05-trello-clone-MohamedAbouDabous#1]
- Widget is not a widget - see the [widget factory documentation](https://jqueryui.com/widget/) or [jquery-boilerplate](https://jqueryboilerplate.com/) site for more guidance
- Remove unnused imports ([line 6](https://github.com/chas-academy/05-trello-clone-MohamedAbouDabous/blob/master/src/js/app.js#L6))

**Comment by MohamedAbouDabous** [comment]
Fixed widget i hope
